# ROOT_REPO/namespaces/bookstore/operator-rolebinding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operator
  namespace: bookstore
subjects:
- kind: User
  name: ekitson@google.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
